name: package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - uses: chartboost/ruff-action@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip install ruff
        pip install -r docs/requirements.txt
        pip install .
 
    - name: Build documentation and examples
      run: |
        sphinx-build -b html docs docs/_build
        sphinx-build -b doctest docs docs/_build

    - name: Run tests and generate coverage data
      run: |
        python3 -m pip install coverage pytest
        coverage run -m pytest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
